name: Build Extension

on:
    push:
        tags:
            - "v*"

permissions:
    contents:
        write

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4

            - name: Install Dependencies
              run: npm install

            - name: Gulp Build
              run: gulp build --ver ${{ github.ref_name }}
            
            
            
            - name: Ammend Version Change
              run: |
                git config --local user.email "action@github.com"
                git config --local user.name "Github Action"

                git stash
                git pull --rebase origin master
                git checkout master
                git pop

                git add src/chrome/manifest.json
                git add src/firefox/manifest.json
                git commit --amend --no-edit
                git push
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Publish Release
              uses: softprops/action-gh-release@v2
              with:
                release_name: ${{ github.ref }}

                files: |
                  dist/*.zip
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}