name: Build Extension

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout

            - name: Setup Node
              uses: actions/setup-node

            - name: Install Dependencies
              run: npm install
            
            - name: Gulp Build
              run: gulp build
            
            - name: Upload build artifacts
              uses: actions/upload-artifact
              with:
                name: extension-build
                path: dist