name: Build Extension

on:
    push:
        branches:
            - master
        tags:
            - "v*"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4

            - name: Install Dependencies
              run: npm install
            
            - name: Gulp Build
              run: gulp build
            
            - name: Ammend Version Change
              run: |
                git config --local user.email "action@github.com"
                git config --local user.name "Github Action"
                git add src/chrome/manifest.json
                git add src/firefox/manifest.json
                git commit --amend --no-edit
                git push -f
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


            - name: Publish Release
              uses: softprops/action-gh-release@v2
              with:
                release_name: ${{ github.ref }}

                files: |
                  dist/*.zip
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}